server:
  port: 8081

spring:
  # profiles:
  #   active: prod

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8085

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:

      # Resource Server - incoming JWT validate karne ke liye
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/back-microservice-h-u-r

      # OAuth2 Client - internal service-to-service token ke liye
      client:
        registration:
          my-internal-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: mic-uhr
            client-secret: v7JJ6YV0w8KJdqpfzFosePuFGzLTXHMzPwK7BsKwuqv8EquDJx49ufJoLmRqwBdfJrE6ZT5A1DJiks1HVa9Lao
            scope:
              - internal

        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/back-microservice-h-u-r

# eureka:
#   instance:
#     prefer-ip-address: true
#
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#
#     service-url:
#       defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDuration: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s